Return last recorded frame for snapshot endpoint
puhitaku/mtplvcap pull request #62
Opened 2022-08-19 18:43 UTC by scraton

As mentioned in #61, this change returns the last frame for the snapshot endpoint, allowing the program to return the last frame even if the camera is disabled.

It seems this data was already being stored, so just returning a copy of that was all that was necessary. The extra code removals here were done to clean up cruft that was no longer necessary.

2022-08-21 06:57 UTC, puhitaku requested changes
I honestly forgot some part of the detail under the hood, but anyway, I've tested the updated one, and it serves the last frame after disconnecting my D5300 🎉 

Two things are left before merging:
1. Please merge the SnapshotResponseWriter into the handler and remove `snapshot.go`.
2. There is an unwanted master-merge commit 3698d01. Please rebase your master branch to the upstream (= my) master branch. Generally speaking, committing your change into a non-master branch is better not to encounter this kind of ambiguation.

2022-08-21 06:57 UTC, puhitaku commented on mtp/server.go
> +	writer.Write(jpeg)
We no longer need a struct `SnapshotResponseWriter`. Let's have all handling done here.

```suggestion
	w.Header().Set("Content-Type", "image/jpeg")
	w.Write(jpeg)
```

2022-08-22 18:02 UTC, scraton commented
Cool :+1: Changes applied, let me know if it looks up to par.

2022-08-23 16:18 UTC, puhitaku approved these changes
LGTM

2022-08-23 16:18 UTC, merged

2022-08-23 17:11 UTC, puhitaku commented
I've bumped and released [version 1.6.0](https://github.com/puhitaku/mtplvcap/releases/tag/v1.6.0)! Thank you for your contribution!